# Generated by Django 2.1.7 on 2019-04-18 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre', 'apellido'],
                'permissions': (('can_mark_returned', 'Set book as returned'),),
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingresa una editorial', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('titulo', models.CharField(max_length=200)),
                ('edicion', models.CharField(max_length=200)),
                ('lugar', models.CharField(max_length=200)),
                ('cubierta', models.CharField(blank=True, choices=[('d', 'Dura'), ('b', 'Blanda')], default='d', max_length=1)),
                ('paginas', models.CharField(max_length=200)),
                ('estanteria', models.CharField(blank=True, choices=[('x', 'Estanteria A'), ('y', 'Estanteria B'), ('z', 'Estanteria C')], default='x', max_length=1)),
                ('comentario', models.TextField(help_text='Ingrese la synopsis del libro', max_length=1000)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.Autor')),
                ('editorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.Editorial')),
            ],
        ),
        migrations.CreateModel(
            name='LibroExistente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID para esta copia del libro', primary_key=True, serialize=False)),
                ('retorno', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('p', 'Prestamo'), ('d', 'Disponible'), ('r', 'Reservado')], default='d', max_length=1)),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.Libro')),
                ('prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['retorno'],
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='borrower',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
