# Generated by Django 2.1.7 on 2019-04-19 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['usuario'], 'permissions': (('administrador', 'usuariocomun'),)},
        ),
    ]
