# Generated by Django 2.1.7 on 2019-04-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20190419_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['usuario'], 'permissions': (('es_administrador', 'usuario_comun'),)},
        ),
    ]
