# Generated by Django 2.1.7 on 2019-04-21 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20190419_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={},
        ),
    ]
