# Generated by Django 2.1.7 on 2019-04-21 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20190421_0420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['usuario'], 'permissions': (('es_administrador', 'usuario_comun'), ('es_usuario_comun', 'Usuario Comun'))},
        ),
    ]
