# Generated by Django 2.1.7 on 2019-04-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_auto_20190421_0435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['usuario'], 'permissions': (('crear_usuarios', 'Puede crear Usuarios'),)},
        ),
    ]
